version: '3.8'

services:

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: associations
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 5

  app:
    image: dntelisa/asso:1.0.0
    container_name: helloworld-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8443:8443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/associations
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  db_data:
